export type Evidence="verified"|"mixed"|"oral"|"legend";export type Story={id:string;title:string;category:string;evidence:Evidence;region:string;summary:string;details:string[]};export const stories:Story[]=[
{id:"hal",title:"Haldighati",category:"Battle",evidence:"mixed",region:"Mewar • 1576",summary:"A major sixteenth-century confrontation remembered through historical accounts and later heroic memory.",details:["18 June 1576","Maharana Pratap • Raja Man Singh I","Chetak and Jhala Man traditions","Separate documented events from later retellings."]},
{id:"pabuji",title:"Pabuji Ri Phad",category:"Folk Epic",evidence:"oral",region:"Western Rajasthan",summary:"A heroic oral epic performed with a painted phad and music, connecting vows, cattle, warfare and devotion.",details:["Bhopa/Bhopi performance","Painted scroll + oral narration","Ravanhattho tradition"]},
{id:"devnarayan",title:"Devnarayan / Bagadawat",category:"Heroic Epic",evidence:"oral",region:"Eastern & Central Rajasthan",summary:"A long oral narrative around the Bagadawat brothers and Devnarayan, combining battle episodes and divine elements.",details:["Bhopa performance","Clan conflict • devotion • heroism","Versions differ by region and narrator"]},
{id:"goga",title:"Goga Gatha",category:"Folk Deity",evidence:"oral",region:"Northwestern Rajasthan",summary:"Warrior and folk-deity traditions surrounding Gogaji, remembered through songs, pilgrimage and serpent lore.",details:["Gogaji / Goga Pir","Devotional and oral performance"]},
{id:"chittor",title:"Chittorgarh Siege Cycle",category:"Siege",evidence:"mixed",region:"Chittorgarh",summary:"The 1303, 1535 and 1567–68 sieges form a major cycle of Rajasthan war memory.",details:["Chittorgarh Fort","Siege • resistance • jauhar/saka traditions","Gora • Badal • Jaimal • Patta"]},
{id:"khanwa",title:"Khanwa",category:"Battle",evidence:"verified",region:"Khanwa • 1527",summary:"A major early-sixteenth-century battle involving Rana Sanga and Babur.",details:["1527","Rana Sanga • Babur","Connect to Mewar and Mughal expansion"]},
{id:"dewair",title:"Dewair",category:"Battle",evidence:"verified",region:"Mewar • 1582",summary:"A Mewar campaign associated with continued resistance and recovery of positions.",details:["1582","Maharana Pratap","Military campaign"]},
{id:"durgadas",title:"Durgadas Rathore",category:"Heroic Figure",evidence:"mixed",region:"Marwar • 17th century",summary:"A major Marwar figure whose resistance became part of later heroic memory.",details:["Marwar","Resistance • diplomacy • mobility"]},
{id:"tarain",title:"Tarain Traditions",category:"Battle Cycle",evidence:"mixed",region:"Chahamana context • 1191–1192",summary:"The battles of Tarain became central to later literary and heroic traditions around Prithviraj Chauhan.",details:["1191 and 1192","Historical accounts + later heroic literature"]},
{id:"auwa",title:"Auwa Resistance",category:"Resistance",evidence:"mixed",region:"Marwar • 1857–58",summary:"Resistance around Auwa entered regional political memory alongside narratives of the 1857 upheaval.",details:["1857–58","Resistance • princely politics • colonial conflict"]}];
export const folklore=[["Dhola–Maru","Love Legend","oral","Western Rajasthan","A celebrated romance of separation, travel, loyalty and reunion."],["Moomal–Mahendra","Love Legend","oral","Western Rajasthan","A famous story of love, disguise, misunderstanding and loss."],["Tejaji Gatha","Folk Deity / Hero","oral","Central & Eastern Rajasthan","A tradition centred on promises, protection, sacrifice and worship."],["Ramdevji Lore","Devotional Tradition","mixed","Western Rajasthan","Stories, songs and pilgrimage traditions around Ramdevji."],["Jasma–Odan","Tragic Legend","oral","Rajasthan","A woman-centred narrative associated with labour, love, honour and tragedy."],["Gavari Stories","Tribal Theatre","oral","Mewar • Bhil communities","Ritual theatre combining mythology, humour and community memory."],["Gopichand–Bharthari","Devotional Epic","oral","Northwestern India","A renunciation and spiritual quest tradition transmitted through song."],["Batan Ri Phulwari","Folktale Collection","oral","Marwar / Thar","A major literary collection rooted in Rajasthan's oral storytelling culture."]].map((x,i)=>({id:"f"+i,title:x[0],category:x[1],evidence:x[2] as Evidence,region:x[3],summary:x[4]}));
export const dynasties=[["Mewar","Guhila / Sisodia","Chittorgarh → Udaipur","☼","Solar lineage tradition • major fort network • resistance memory"],["Marwar","Rathore","Mandore → Jodhpur","𓅃","Desert kingdom • cavalry • trade routes • heroic traditions"],["Amber / Jaipur","Kachhwaha","Amber → Jaipur","◉","Court culture • astronomy • imperial diplomacy"],["Bikaner","Rathore","Bikaner","✦","Desert frontier • camel culture"],["Jaisalmer","Bhati","Jaisalmer","◇","Fortified desert city • caravan trade"],["Bundi","Hada Chauhan","Bundi","⌁","Hadoti • hill fort • miniature painting"],["Kota","Hada Chauhan","Kota","◈","Hadoti • Chambal • courtly arts"],["Karauli","Yaduvanshi tradition","Karauli","✥","Temple patronage • princely-state history"]].map((x,i)=>({id:"d"+i,name:x[0],house:x[1],capital:x[2],symbol:x[3],context:x[4]}));
export const places=[["Jaisalmer",26.9157,70.9083,"Bhati tradition • Jaisalmer Fort • desert trade"],["Bikaner",28.0229,73.3119,"Bikaner state • Junagarh Fort • desert ecology"],["Jodhpur",26.2389,73.0243,"Marwar • Rathore history • Mehrangarh"],["Jaipur",26.9124,75.7873,"Amber/Jaipur • Kachhwaha • Jantar Mantar"],["Ajmer",26.4499,74.6399,"Chahamana history • pilgrimage"],["Chittorgarh",24.8887,74.6269,"Mewar • siege cycle • Chittorgarh Fort"],["Udaipur",24.5854,73.7125,"Mewar • lakes • later capital"],["Kota",25.2138,75.8648,"Hadoti • Kota state • Chambal"]].map((x,i)=>({id:"p"+i,name:x[0],lat:x[1],lng:x[2],summary:x[3]}));